# Generated by Django 6.1 on 2026-08-10 16:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(default='India', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/destinations/')),
                ('image_url', models.URLField(blank=True, help_text='Optional web image, used when no file is uploaded.')),
                ('estimated_cost_per_day', models.DecimalField(decimal_places=2, default=Decimal('2500.00'), help_text='SAMPLE estimate per person per day, in rupees.', max_digits=10)),
                ('recommended_days', models.PositiveSmallIntegerField(default=3)),
                ('is_popular', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('cost_per_km', models.DecimalField(decimal_places=2, help_text='SAMPLE rupees per kilometre.', max_digits=8)),
                ('average_speed_kmph', models.PositiveSmallIntegerField(default=50)),
                ('seats_per_unit', models.PositiveSmallIntegerField(default=1, help_text='How many people share one vehicle (Car=4, Bike=2). Use 1 for per-person tickets like bus/train.')),
                ('charged_per_person', models.BooleanField(default=False, help_text='True for bus/train (ticket per person).')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Transportation options',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('te', 'Telugu')], default='en', max_length=5)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='uploads/avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RouteDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city', models.CharField(max_length=100)),
                ('to_city', models.CharField(max_length=100)),
                ('distance_km', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['from_city', 'to_city'],
                'unique_together': {('from_city', 'to_city')},
            },
        ),
        migrations.CreateModel(
            name='TouristPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/places/')),
                ('image_url', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('beach', 'Beach'), ('temple', 'Temple'), ('historical', 'Historical'), ('nature', 'Nature'), ('shopping', 'Shopping'), ('museum', 'Museum'), ('adventure', 'Adventure'), ('food', 'Food')], default='historical', max_length=20)),
                ('opening_info', models.CharField(blank=True, help_text="e.g. 'Open 9 AM - 6 PM, closed Monday'", max_length=200)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='SAMPLE entry fee per person, in rupees.', max_digits=8)),
                ('visit_duration_minutes', models.PositiveSmallIntegerField(default=90, help_text='Roughly how long a visit takes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='travel.destination')),
            ],
            options={
                'ordering': ['destination__name', 'name'],
                'unique_together': {('destination', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=140)),
                ('source', models.CharField(help_text='Starting city, e.g. Pune', max_length=100)),
                ('travel_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('travelers', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('days', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('hotel_category', models.CharField(choices=[('budget', 'Budget'), ('standard', 'Standard'), ('deluxe', 'Deluxe'), ('luxury', 'Luxury')], default='standard', max_length=20)),
                ('food_budget', models.CharField(choices=[('budget', 'Budget'), ('standard', 'Standard'), ('premium', 'Premium')], default='standard', max_length=20)),
                ('activity_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('distance_km', models.PositiveIntegerField(default=0)),
                ('travel_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('itinerary_text', models.TextField(blank=True, help_text='Generated day-by-day plan.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved'), ('completed', 'Completed')], default='saved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='travel.destination')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='travel.transportation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hotel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('food_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('local_transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activity_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='travel.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField(default=1)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.touristplace')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_places', to='travel.trip')),
            ],
            options={
                'ordering': ['day_number', 'order'],
                'unique_together': {('trip', 'place')},
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='trips', through='travel.TripPlace', to='travel.touristplace'),
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/recognition/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('recognition_result', models.TextField(blank=True)),
                ('is_confident', models.BooleanField(default=False, help_text='False means the AI was not sure about the place.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Customer'), ('assistant', 'AI Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('language', models.CharField(default='en', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='travel.uploadedimage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
