# Generated by Django 6.1 on 2026-08-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional web image, used when no file is uploaded.', max_length=500),
        ),
        migrations.AlterField(
            model_name='touristplace',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
