# Generated by Django 6.1 on 2026-08-20 10:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_destination_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('display_order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='destination',
            name='best_time',
            field=models.CharField(blank=True, help_text="e.g. 'October to March'. Free text, shown on the card.", max_length=90),
        ),
        migrations.AddField(
            model_name='destination',
            name='sample_rating',
            field=models.DecimalField(decimal_places=1, default=Decimal('4.0'), help_text='ILLUSTRATIVE score for the demo, in the same spirit as the sample prices. It is NOT an average of real visitor reviews, and the template labels it so - never present it as one.', max_digits=2),
        ),
        migrations.AddField(
            model_name='destination',
            name='themes',
            field=models.ManyToManyField(blank=True, help_text='Who the trip suits: family, honeymoon, weekend and so on.', related_name='destinations', to='travel.theme'),
        ),
    ]
