# Generated by Django 6.1 on 2026-08-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_theme_destination_best_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='kind',
            field=models.CharField(choices=[('trip', 'Trip theme'), ('pilgrimage', 'Pilgrimage circuit')], default='trip', max_length=12),
        ),
    ]
