# Generated by Django 6.1 on 2026-08-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_theme_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image_url',
            field=models.CharField(blank=True, help_text='Optional picture, used when no file is uploaded. Either a path like /static/images/destinations/goa.jpg or a full web address.', max_length=500),
        ),
        migrations.AlterField(
            model_name='touristplace',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
