# Generated by Django 6.1 on 2026-08-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_destination_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('te', 'Telugu (తెలుగు)'), ('hi', 'Hindi (हिन्दी)'), ('ta', 'Tamil (தமிழ்)'), ('kn', 'Kannada (ಕನ್ನಡ)'), ('ml', 'Malayalam (മലയാളം)'), ('mr', 'Marathi (मराठी)'), ('bn', 'Bengali (বাংলা)'), ('gu', 'Gujarati (ગુજરાતી)'), ('pa', 'Punjabi (ਪੰਜਾਬੀ)'), ('ur', 'Urdu (اردو)'), ('or', 'Odia (ଓଡ଼ିଆ)')], default='en', max_length=5),
        ),
    ]
