# Generated by Django 6.1 on 2026-08-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_citylocation_destination_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('te', 'Telugu (తెలుగు)')], default='en', max_length=5),
        ),
    ]
